platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 2.0.0'
pod 'AFNetworking', '~> 2.2.1'
pod 'IOSLinkedInAPI'
pod 'Firebase', '~> 1.0.0'
pod 'Mantle', '~> 1.3'
pod 'APToast'
pod 'JASidePanels', '~> 1.3.2'
pod 'box-ios-sdk-v2', '~> 1.2'